name: jeplulu
favicon: null
layout_spectrum: 0.50764
typography_spectrum: 0.59127
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2929206828121096
  lightness: 0.14752289233729243
  saturation: 0.9017590789590031
  rhythmicContrast: 0.5688752953428775
purpose: []
