title: photographer. traveller. pulpo.
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.2741936
  brandStrength: 1
  lightness: 0.1475229
  brandColors:
    - '#FFFFFE'
    - '#353534'
    - '#9F9F9E'
    - '#676867'
    - '#CACBCA'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: jeplulu
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.58722
layout_spectrum: 1
