name: jeplulu
favicon: null
layout_spectrum: 0.01098
typography_spectrum: 0.58722
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFE'
    - '#353534'
    - '#9F9F9E'
    - '#676867'
    - '#CACBCA'
  brandStrength: 0.75
  lightness: 0.1475228923372924
  saturation: 0.875
  rhythmicContrast: 0.5688752953428775
purpose: []
